[target.i686-pc-windows-msvc.freetype]
rustc-link-search = ["C:\\dev\\vendor\\freetype\\binaries\\i686"]
rustc-link-lib = ["freetype"]

[target.x86_64-pc-windows-msvc.freetype]
rustc-link-search = ["C:\\dev\\vendor\\freetype\\binaries\\x86_64"]
rustc-link-lib = ["freetype"]